"""Add normalization columns

Revision ID: 83518df56015
Revises: 
Create Date: 2025-12-31 20:35:21.403020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83518df56015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search', 'episode_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('search', 'podcast',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('transcriptions', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('transcriptions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('transcriptions', sa.Column('published_date', sa.DateTime(), nullable=True))
    op.add_column('transcriptions', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcriptions', 'url')
    op.drop_column('transcriptions', 'published_date')
    op.drop_column('transcriptions', 'description')
    op.drop_column('transcriptions', 'title')
    op.alter_column('search', 'podcast',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('search', 'episode_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
