"""Add Podcast table and FK

Revision ID: ee79e9a2984f
Revises: 83518df56015
Create Date: 2025-12-31 20:40:21.119865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee79e9a2984f"
down_revision: Union[str, Sequence[str], None] = "83518df56015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "podcasts",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("feed_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Insert default podcast "Conduit" to ensure FK constraint is satisfied for existing data
    op.execute(
        "INSERT INTO podcasts (id, title, description) VALUES ('Conduit', 'Conduit', 'Productivity podcast')"
    )

    op.create_foreign_key(None, "transcriptions", "podcasts", ["podcast"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transcriptions", type_="foreignkey")
    op.drop_table("podcasts")
    # ### end Alembic commands ###
